### ISSUE TITLE
Unable to build crx file

### ISSUE THREAD

**Issue by elnurgo** [cardinalby/webext-buildtools-chrome-crx-action#10]
Hi, a couple of days ago my workflows started giving error on crx build step:
```
Run cardinalby/webext-buildtools-chrome-crx-action@v2
  with:
    zipFilePath: ./zippath.zip
    crxFilePath: ./crxpath.crx
    privateKey: ***
  
  env:
    NODE_ENV: development
    GCP_EMAIL: ***
    GCP_KEY: ***
  
    CRX_SIGNING_KEY: ***
  
    BUCKET_PROJECT_ID: shared-artifacts-public-6dcd
    CRX_PUBLISH_URL: gs://...
    UPDATEXML_PUBLISH_URL: gs://..
    UPDATE_CHECK_PATH_FOLDER: dev
    APPID: cpoobmpplofdecaacojaflkimgpndfck
    BUILD_NUMBER: 461
    APPNAME: DEV
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../declarations/options'
Require stack:
- /home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v[2]/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9[3]
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.686 (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:88300:33)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:88528:[4]()3)
    at Object.4[5]()81 (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:82031:14)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:88528:43)
    at Object.3109 (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:10[6]():64)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:88528:43)
    at /home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:88560:3[7]()
    at Object.<anonymous> (/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js:[8]()8563:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:[9]()81:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12]()) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/cardinalby/webext-buildtools-chrome-crx-action/v2/dist/index.js'
  ]
***

```

**Comment by cardinalby** [comment]
@elnurgo 
Hi! Thanks for reporting and sorry for the breaking your CI, I was fixing security alerts in dependencies and just don't have enough tests :(

I will take a look and fix it ASAP. As a hotfix use `@2.0.1` version. You can also pinpoint the version by commit SHA.

**Comment by elnurgo** [comment]
Thanks for fast response. Closing the issue.
